[package]
name = "aous"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/mockersf/bevy", branch = "fix-linear", default-features = false, features = [
  "bevy_core_pipeline",
  "bevy_sprite2",
  "bevy_render2",
  "bevy_pbr2",
  "bevy_winit",
  "x11",
] }
bracket-noise = "0.8"
# bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast" }
rand = "0.8"

[profile.dev.package."*"]
opt-level = 3
