[package]
name = "aous"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bracket-noise = "0.8"
bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast" }

[profile.dev.package."*"]
opt-level = 3
